/**acao é um objeto dummy só para naão dar erro inicialmente */
export const acao = {
    radarRealtime: {
        TICKER: "",
        qotacao: "",
        deltaPreco: "",
        deltaVol: "",
        theGap: "",
        dyNow: "",
        atualPorMM9: "",
        atualPorMM20: "",
        atualPorMM45: "",
        dataPesquisa: "",
        opcoesAtmSugeridas: "",
    },
    dividaliq: {
        TICKER: "",
        divliquida: "",
        dataPesquisa: "",
    },
    fundamentos: {
        TICKER: "",
        Cotacao: "",
        PL: "",
        PVP: "",
        PSR: "",
        DivYield: "",
        PAtivo: "",
        PCapGiro: "",
        PEBIT: "",
        PAtivCircLiq: "",
        EVEBITDA: "",
        MrgEbit: "",
        MrgLiq: "",
        LiqCorr: "",
        ROIC: "",
        ROE: "",
        Liq2meses: "",
        PatrimLiq: "",
        DivBrutPatrim: "",
        CrescRec5a: "",
    },
    yahoofinance: {
        TICKER: "",
        Data: "",
        Abrir: "",
        Alto: "",
        Baixo: "",
        Fechamento: "",
        FechamentoAjustado: "",
        Volume: "",
        VolMedio21: "",
        dataPesquisa: "",
    },
    rsiData: {
        TICKER: "",
        RSI: "",
        dataPesquisa: "",
        RSI_ST_FAST: "",
    },
    opcoesAtmListCalculadas: [
        {
            optTicker: "",
            tipo: "",
            premio: "",
            strike: "",
            data: "",
            TICKER: "",
            coacaoAtivo: "",
        }
    ]
}